### ISSUE TITLE
Usage examples seem to be incorrect

### ISSUE THREAD

**Issue by stephenhutchings** [posthtml/posthtml-base-url#27]
## Problem

The example usage in the [readme.md](https://github.com/posthtml/posthtml-base-url/blob/a9455c10173572a33ff65542d11dec8c6554e255/readme.md?plain=1#L54) doesn't produce the result described, because options are included in the wrong location.

```js
const posthtml = require('posthtml')
const baseUrl = require('posthtml-base-url')

posthtml([
  baseUrl(/* options should be here */)
])
  .process('<img src="test.jpg">', /* but are included here*/ {url: 'https://example.com', allTags: true})
  .then(result => console.log(result.html))
```

Not a major issue, but had me wondering whether the plugin actually worked. After moving the options, the plugin works as expected.

## Environment

- `posthtml-base-url` plugin version: 1.1.0
- PostHTML version: 0.16.6
- Node.js version: 16.4.2

**Comment by cossssmin** [comment]
Thanks for spotting it, fixed now! :)
